# Generated by scripts/update-homebrew-formula.mjs — do not edit by hand.
#
# Homebrew never applies the macOS quarantine attribute, so an installation
# through this formula is not subject to Gatekeeper the way a browser download
# would be.
class Dvalincode < Formula
  desc "Approvable, local-first AI coding agent with a governed security scanner"
  homepage "https://github.com/arthurpanhku/dvalincode"
  version "0.20.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/arthurpanhku/dvalincode/releases/download/v0.20.1/dvalincode-v0.20.1-macos-arm64.tar.gz"
      sha256 "313f64231179389bc6cbd02c6924403ffa4aadc6a2f75906d12fd941df28f153"
    end
    on_intel do
      url "https://github.com/arthurpanhku/dvalincode/releases/download/v0.20.1/dvalincode-v0.20.1-macos-x64.tar.gz"
      sha256 "08f5c97fee77e7c96cb49c893321445a9c6acb11efcabb5d494d51f18c20895c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/arthurpanhku/dvalincode/releases/download/v0.20.1/dvalincode-v0.20.1-linux-arm64.tar.gz"
      sha256 "bf27f66046b5f565f15109bc1393635f554b079dc4949a7e14a010cf29a9ab9c"
    end
    on_intel do
      url "https://github.com/arthurpanhku/dvalincode/releases/download/v0.20.1/dvalincode-v0.20.1-linux-x64.tar.gz"
      sha256 "a22828c50c0b09a084fca8a05340abd6c68cef88063f83e7f9374b097189668e"
    end
  end

  def install
    # The binary resolves its web assets as dirname(execPath)/web/dist, so it
    # has to stay next to the extracted tree. Homebrew resolves the symlink
    # when the executable starts, which keeps that lookup pointing at libexec.
    libexec.install Dir["*"]
    binary = Dir[libexec/"dvalincode-*"].find { |f| File.file?(f) && File.executable?(f) }
    odie "no dvalincode binary in the archive" if binary.nil?
    bin.install_symlink binary => "dvalincode"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/dvalincode --version")
    # Scanning needs no API key, no model, and no config — so the formula can
    # prove the install actually works rather than only that it starts.
    (testpath/"vuln.js").write("app.post('/x', (req, res) => res.send(String(eval(req.body.e))));\n")
    output = shell_output("#{bin}/dvalincode dvalin #{testpath} --scanners builtin --json")
    assert_match "dvalin/eval", output
  end
end
