# Generated by scripts/update-homebrew-formula.mjs — do not edit by hand.
#
# Homebrew never applies the macOS quarantine attribute, so an installation
# through this formula is not subject to Gatekeeper the way a browser download
# would be.
class Dvalincode < Formula
  desc "Approvable, local-first AI coding agent with a governed security scanner"
  homepage "https://github.com/arthurpanhku/dvalincode"
  version "0.21.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/arthurpanhku/dvalincode/releases/download/v0.21.0/dvalincode-v0.21.0-macos-arm64.tar.gz"
      sha256 "b0ab81e8ed3a40cf05e38bc6fe2e0c6da750ab6926da58a09d589f4e84edd787"
    end
    on_intel do
      url "https://github.com/arthurpanhku/dvalincode/releases/download/v0.21.0/dvalincode-v0.21.0-macos-x64.tar.gz"
      sha256 "c5b2497cb2dd3a4e4435a4b137096c286c5169a4aa7463e7d8018d63c2516c8b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/arthurpanhku/dvalincode/releases/download/v0.21.0/dvalincode-v0.21.0-linux-arm64.tar.gz"
      sha256 "b57c28e3bf9c00c73360b7e54cc6616e0baf25a2728495ce95a6f75830207732"
    end
    on_intel do
      url "https://github.com/arthurpanhku/dvalincode/releases/download/v0.21.0/dvalincode-v0.21.0-linux-x64.tar.gz"
      sha256 "c867bb6a00921de3c209e53a6a5f737e89682868c17d055731767ea4aa4b51a6"
    end
  end

  def install
    # The binary resolves its web assets as dirname(execPath)/web/dist, so it
    # has to stay next to the extracted tree. Homebrew resolves the symlink
    # when the executable starts, which keeps that lookup pointing at libexec.
    libexec.install Dir["*"]
    binary = Dir[libexec/"dvalincode-*"].find { |f| File.file?(f) && File.executable?(f) }
    odie "no dvalincode binary in the archive" if binary.nil?
    bin.install_symlink binary => "dvalincode"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/dvalincode --version")
    # Scanning needs no API key, no model, and no config — so the formula can
    # prove the install actually works rather than only that it starts.
    (testpath/"vuln.js").write("app.post('/x', (req, res) => res.send(String(eval(req.body.e))));\n")
    output = shell_output("#{bin}/dvalincode dvalin #{testpath} --scanners builtin --json")
    assert_match "dvalin/eval", output
  end
end
