# Generated by scripts/update-homebrew-formula.mjs — do not edit by hand.
#
# Homebrew never applies the macOS quarantine attribute, so an installation
# through this formula is not subject to Gatekeeper the way a browser download
# would be.
class Dvalincode < Formula
  desc "Approvable, local-first AI coding agent with a governed security scanner"
  homepage "https://github.com/arthurpanhku/dvalincode"
  version "0.16.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/arthurpanhku/dvalincode/releases/download/v0.16.1/dvalincode-v0.16.1-macos-arm64.tar.gz"
      sha256 "752633e5bd76dace0b6bcdc556b879b972a718f5af08341d8ac2d9a9d23addf8"
    end
    on_intel do
      url "https://github.com/arthurpanhku/dvalincode/releases/download/v0.16.1/dvalincode-v0.16.1-macos-x64.tar.gz"
      sha256 "844b15e6ff9fbaae8be71590b2b9c462e27f92750ced01dcea71acbca3891dae"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/arthurpanhku/dvalincode/releases/download/v0.16.1/dvalincode-v0.16.1-linux-arm64.tar.gz"
      sha256 "c8245bcbcd0722027d01e744c3d71a32616f14bbc42372465f4282bf6d15c4dc"
    end
    on_intel do
      url "https://github.com/arthurpanhku/dvalincode/releases/download/v0.16.1/dvalincode-v0.16.1-linux-x64.tar.gz"
      sha256 "59f63e65ba8cdb6ebb5cb80f64b2e8a7c5114a51f005b8a066616fc2f9e7e369"
    end
  end

  def install
    # The binary resolves its web assets as dirname(execPath)/web/dist, so it
    # has to stay next to the extracted tree. Homebrew resolves the symlink
    # when the executable starts, which keeps that lookup pointing at libexec.
    libexec.install Dir["*"]
    binary = Dir[libexec/"dvalincode-*"].find { |f| File.file?(f) && File.executable?(f) }
    odie "no dvalincode binary in the archive" if binary.nil?
    bin.install_symlink binary => "dvalincode"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/dvalincode --version")
    # Scanning needs no API key, no model, and no config — so the formula can
    # prove the install actually works rather than only that it starts.
    (testpath/"vuln.js").write("app.post('/x', (req, res) => res.send(String(eval(req.body.e))));\n")
    output = shell_output("#{bin}/dvalincode dvalin #{testpath} --scanners builtin --json")
    assert_match "dvalin/eval", output
  end
end
